name: asdrome_pos
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  dynamic_color: ^1.6.8
  flutter:
    sdk: flutter
  flutter_adaptive_scaffold: ^0.1.7+1
  flutter_localizations:
    sdk: flutter
  intl: any
  json_annotation: ^4.8.1
  pocketbase: ^0.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  

  flutter_lints: ^3.0.1
  json_serializable: ^6.7.1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
